AWS_DEFAULT_REGION: ""
AWS_S3_ENDPOINT: "js2.jetstream-cloud.org:8001"
DATA_DIR: "/home/rstudio/data"
endpoint_override: "js2.jetstream-cloud.org:8001"
themes:
  phenology:
    targets: 
      - gcc_90
      - rcc_90
    targets_file_name: phenology-targets.csv.gz
    only_forecasts: FALSE
  aquatics:
    targets: 
      - oxygen
      - temperature
    targets_file_name: aquatics-targets.csv.gz
    only_forecasts: FALSE
  terrestrial_30min:
    targets: 
      - nee
      - le
    targets_file_name: terrestrial_30min-targets.csv.gz
    only_forecasts: FALSE
  terrestrial_daily:
    targets: 
      - nee
      - le
    targets_file_name: terrestrial_daily-targets.csv.gz
    only_forecasts: FALSE
  beetles:
    targets: 
      - richness
      - abundance
    targets_file_name: beetles_daily-targets.csv.gz
    only_forecasts: FALSE
  ticks:
    targets:
      - ixodes_scapularis
      - amblyomma_americanum
    targets_file_name: ticks_daily-targets.csv.gz
    only_forecasts: FALSE

