---
title: "EFI-NEON Ecological Forecasting Challenge Dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: "cosmo"
runtime: shiny
---
```{r setup, include = FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(readr)
library(arrow)
library(neon4cast)

#THIS FILE PATH NEEDS TO BE CHANGED - currently set to my local files
Sys.setenv("AWS_EC2_METADATA_DISABLED"="TRUE")
Sys.unsetenv("AWS_ACCESS_KEY_ID")
Sys.unsetenv("AWS_SECRET_ACCESS_KEY")
Sys.unsetenv("AWS_DEFAULT_REGION")
Sys.unsetenv("AWS_S3_ENDPOINT")

challenge_config <- yaml::read_yaml("challenge_config.yml")

#s3 <- arrow::s3_bucket(bucket = "scores",
#                         endpoint_override = paste0(challenge_config$AWS_DEFAULT_REGION,".",challenge_config$AWS_S3_ENDPOINT),
#                         anonymous=TRUE)
#s3 <- "/efi_neon_challenge/local/scores/parquet/"
#ds <- arrow::open_dataset(s3) %>% collect()
theme_choices <- names(challenge_config$themes)
base_date <- as.character(Sys.Date() - lubridate::days(60))

```

Multi-team visualization
=======================================================================

Pick Forecast Category {.sidebar}
-----------------------------------------------------------------------

```{r}
renderUI({
  selectInput("forecast", "Select forecast theme:", 
              #choices = theme_choices, selected = "aquatics")
              choices = theme_choices, selected = theme_choices[1])
})

combined <- reactive({

  #s3 <- arrow::s3_bucket(paste0("neon4cast-scores/parquet/",input$forecast) , endpoint_override=challenge_config$endpoint_override)
  s3 <- SubTreeFileSystem$create(paste0(challenge_config$DATA_DIR, "/scores/parquet/",input$forecast))
  #s3 <- paste0(challenge_config$DATA_DIR, "/scores/parquet/",input$forecast)
  ds <- arrow::open_dataset(s3)
  
  df <- ds %>% filter(reference_datetime > base_date &
                      !(model_id == "persistenceRW" & variable == "chla")) %>%
  collect()
  print(df)
  df
  #ds %>% filter(reference_datetime > base_date,
  #              !(model_id == "persistenceRW" & variable == "chla")) %>%
  #collect()
})

potential_dates <- reactive({
   df <-  unique(combined()$reference_datetime)
   sort(lubridate::as_date(df), decreasing = TRUE)

})

renderUI({
  selectInput("date", "Select forecast start date:", 
              choices = potential_dates(), selected = potential_dates()[1])
})

file.teams <- reactive({
  df <- combined() %>% filter(lubridate::as_date(reference_datetime) == lubridate::as_date(input$date))
  unique(df$model_id)
})

renderUI({
  selectInput("team", "Select forecast team (multiple selections allowed):", 
              choices = file.teams(), selected = file.teams()[1], multiple = TRUE)
})

potential_targets <- reactive({
  df <- combined() %>% filter(lubridate::as_date(reference_datetime) == lubridate::as_date(input$date),
                              model_id %in% input$team)
  unique(df$variable)
})

renderUI({
  radioButtons("target", "Select forecast target:", 
              choices = potential_targets(), selected = potential_targets()[1])
})

sites <- reactive({
  df <- combined() %>% filter(lubridate::as_date(reference_datetime) == lubridate::as_date(input$date),
                              model_id %in% input$team)
  unique(df$site_id)
})

renderUI({
  selectInput("facet", "Select site ID for plot panels:", 
              choices = sites(), selected = sites()[1:5], multiple = TRUE)
})


team_date_forecast <-reactive({
  combined() %>% filter(model_id %in% input$team,
                        lubridate::as_date(reference_datetime) == lubridate::as_date(input$date),
                        variable == input$target,
                        site_id %in% input$facet
  )
})

```

Forecast Plot 
-------------------------------------

```{r}
target.plot <- reactive({
  
  print(team_date_forecast())
  
  team_date_forecast() %>% 
    ggplot(aes(x = datetime, y = mean, color = model_id)) +
    geom_ribbon(aes(ymin = quantile02.5, ymax = quantile97.5, color = model_id, fill = model_id), alpha = 0.3) +
    geom_line(aes(y = mean, color = model_id)) +
    geom_point(aes(y = observation), color = "black") +
    facet_wrap(~site_id) +
    labs(x = "time", y = input$target)
})

renderPlot({
  
  target.plot()
  
})
```

Multi-date visualization
=======================================================================

Pick Forecast Category {.sidebar}
-----------------------------------------------------------------------

```{r}

renderUI({
  selectInput("forecast2", "Select forecast theme:", 
              choices = theme_choices, selected = theme_choices[1])
})

combined2 <- reactive({
  
  s3_2 <- SubTreeFileSystem$create(paste0(challenge_config$DATA_DIR, "/scores/parquet/",input$forecast))
  ds_2 <- arrow::open_dataset(s3_2)
  df2 <- ds_2 %>% filter(reference_datetime > base_date,
                !(model_id == "persistenceRW" & variable == "chla")) %>%
  collect()
  print(df2)
  df2
})

file.teams2 <- reactive({
    print(combined2())
  unique(combined2()$model_id)
})

renderUI({
  selectInput("team2", "Select forecast team:", 
              choices = file.teams2(), selected = file.teams2()[1])
})

potential_dates2 <- reactive({
  df <- combined2() %>% filter(model_id == input$team2)
  df <-  unique(df$reference_datetime)
   sort(lubridate::as_date(df), decreasing = TRUE)
})

renderUI({
  selectInput("date2", "Select forecast start date (multiple selections allowed):", 
              choices = potential_dates2(), selected = potential_dates2()[1], multiple = TRUE)
})

potential_targets2 <- reactive({
  df <- combined2() %>% filter(lubridate::as_date(reference_datetime) %in% lubridate::as_date(input$date2),
                               model_id == input$team2)
  unique(df$variable)
})

renderUI({
  radioButtons("target2", "Select forecast target:", 
              choices = potential_targets2(), selected = potential_targets2()[1])
})



sites2 <- reactive({
  df <- combined2() %>% filter(lubridate::as_date(reference_datetime) == lubridate::as_date(input$date2),
                              model_id == input$team2)
  unique(df$site_id)
})

renderUI({
  selectInput("facet2", "Select site ID for plot panels:", 
              choices = sites2(), selected = sites2()[1:5], multiple = TRUE)
})

team_date_forecast2 <-reactive({
  combined2() %>% filter(model_id == input$team2,
                         lubridate::as_date(reference_datetime) %in% lubridate::as_date(input$date2),
                         variable == input$target2,
                         site_id %in% input$facet2
  )
})


```

Forecast Plot 
-------------------------------------

```{r}
target.plot2 <- reactive({
  
  team_date_forecast2() %>% 
    mutate(reference_datetime = factor(reference_datetime)) %>% 
    ggplot(aes(x = datetime, y = mean, color = reference_datetime)) +
    geom_ribbon(aes(ymin = quantile02.5, ymax = quantile97.5, color = reference_datetime, fill = reference_datetime), alpha = 0.3) +
    geom_line(aes(y = mean, color = reference_datetime)) +
    geom_point(aes(y = observation), color = "black") +
    facet_wrap(~site_id) +

    labs(x = "time", y = input$target2)
})

renderPlot({
  
  target.plot2()
  
})
```
