on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

name: gefs-stage3

jobs:
  docker:
    runs-on: [self-hosted]
    timeout-minutes: 1440
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          remotes::install_github("eco4cast/neon4cast"); install.packages(c("neonstore", "imputeTS"))
        shell: Rscript {0}
        name: install deps
      - run: |
          Rscript -e "source('gefs4cast-stage3.R')"
        name: Update Inventory

